### ISSUE TITLE
Error: connect ECONNREFUSED 151.101.0.133:443

### ISSUE THREAD

**Issue by mactrash** [apostrophecms/apostrophe-cli#26]
I am new to this and I just follow the step to install all the programs, and while I try

 apostrophe create-project test-project

It result error

/usr/local/lib/node_modules/apostrophe-cli/node_modules/sync-rpc/lib/index.js:167
    throw error;
    ^

Error: connect ECONNREFUSED 151.101.0.133:443

Do I did something wrong? How can I fix this?

**Comment by boutell** [comment]
The `apostrophe` command is unable to access the URL `https://raw.githubusercontent.com/apostrophecms/apostrophe-boilerplate/master/package.json` from your particular computer, server, or whatever environment you are running the command in. Most likely a firewall issue on your end. I have retested to make sure and these commands do work. Closing for housekeeping as this is not a bug.
